// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProfile(arg1) {
  return window['go']['main']['App']['ApplyProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetAudioDeviceNickname(arg1) {
  return window['go']['main']['App']['GetAudioDeviceNickname'](arg1);
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetAudioDevicesWithIgnoreStatus() {
  return window['go']['main']['App']['GetAudioDevicesWithIgnoreStatus']();
}

export function GetMonitorNickname(arg1) {
  return window['go']['main']['App']['GetMonitorNickname'](arg1);
}

export function GetMonitorStates() {
  return window['go']['main']['App']['GetMonitorStates']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSelectedAudioDevices() {
  return window['go']['main']['App']['GetSelectedAudioDevices']();
}

export function IgnoreAudioDevice(arg1) {
  return window['go']['main']['App']['IgnoreAudioDevice'](arg1);
}

export function RefreshAudioDevices() {
  return window['go']['main']['App']['RefreshAudioDevices']();
}

export function RefreshMonitors() {
  return window['go']['main']['App']['RefreshMonitors']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SetAudioDeviceNickname(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDeviceNickname'](arg1, arg2);
}

export function SetAudioDeviceSelection(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDeviceSelection'](arg1, arg2);
}

export function SetDefaultAudioDevice(arg1) {
  return window['go']['main']['App']['SetDefaultAudioDevice'](arg1);
}

export function SetMonitorEnabledState(arg1, arg2) {
  return window['go']['main']['App']['SetMonitorEnabledState'](arg1, arg2);
}

export function SetMonitorNickname(arg1, arg2) {
  return window['go']['main']['App']['SetMonitorNickname'](arg1, arg2);
}

export function SetMonitorPrimary(arg1) {
  return window['go']['main']['App']['SetMonitorPrimary'](arg1);
}

export function UnignoreAudioDevice(arg1) {
  return window['go']['main']['App']['UnignoreAudioDevice'](arg1);
}
